### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mopped7** [Blitoka33/bltk_anticheat#2]
The log with the player information could be assigned to the screenshot attachment, preventing them from being separated and causing confusion between a screenshot and a log from another player.

That is, every time a detection is made, generate the log with all the offender's information and the screenshot, all in the same attachment. ;)

**Comment by Blitoka33** [comment]
I will make it for some functions, not every because that would open another bypass option, I don’t want to bring server-side detections to client-side to make them bypassable, at the moment the screenshot log channel is made for the screen analyzer OCR ai, or to store temp screenshots generated with the screenshot admin command. The screenshots generated with the admin command are embedded into a log message, so in that case you will be able to see the correct screenshot, I will do the same logic for some detections. Thanks for the suggestion.

Best regards,
Blitoka33

**Comment by Blitoka33** [comment]
In the next major update the overall log system will be reworked.
